# Generated by Django 3.0.7 on 2020-07-14 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_pref', models.CharField(choices=[('French', 'French'), ('YDS', 'YDS'), ('Aus', 'Aus'), ('UIAA', 'UIAA'), ('SA', 'SA'), ('UK', 'UK')], default='French', max_length=20, verbose_name='Grading system user preference')),
                ('measurement_pref', models.CharField(choices=[('meters', 'meters'), ('feet', 'feet')], default='meters', max_length=20, verbose_name='Measurement system preference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
