# Generated by Django 3.0.7 on 2020-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='grade_pref',
            field=models.CharField(choices=[('French', 'French'), ('YDS', 'YDS')], default='French', max_length=20, verbose_name='Grading system user preference'),
        ),
    ]
