# Generated by Django 3.0.7 on 2020-07-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crag',
            name='cdescription',
            field=models.TextField(default='', verbose_name='Crag description'),
            preserve_default=False,
        ),
    ]
