# Generated by Django 2.1.2 on 2018-10-14 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crag',
            name='c_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Page author'),
        ),
        migrations.AlterField(
            model_name='crag',
            name='c_description',
            field=models.TextField(verbose_name='Crag description'),
        ),
        migrations.AlterField(
            model_name='crag',
            name='c_name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
    ]
