# Generated by Django 2.1.2 on 2018-10-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0002_auto_20181014_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crag',
            old_name='c_author',
            new_name='cauthor',
        ),
        migrations.RenameField(
            model_name='crag',
            old_name='c_description',
            new_name='cdescription',
        ),
        migrations.RenameField(
            model_name='crag',
            old_name='c_name',
            new_name='cname',
        ),
    ]
