# Generated by Django 3.0.7 on 2020-07-17 07:03

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0002_crag_cdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='crag',
            name='location',
            field=djgeojson.fields.PointField(default=''),
            preserve_default=False,
        ),
    ]
