# Generated by Django 3.0.7 on 2020-07-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0003_crag_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crag',
            old_name='location',
            new_name='geom',
        ),
    ]
