# Generated by Django 3.0.7 on 2020-07-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0004_auto_20200717_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crag',
            old_name='geom',
            new_name='location',
        ),
    ]
