# Generated by Django 3.0.8 on 2020-08-03 14:14

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0007_auto_20200717_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crag',
            name='cdescription',
            field=django_quill.fields.QuillField(max_length=50000, verbose_name='Crag description'),
        ),
    ]
