# Generated by Django 3.0.8 on 2020-08-04 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crags', '0008_auto_20200803_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crag',
            name='cauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Page author'),
        ),
    ]
