# Generated by Django 3.0.7 on 2020-06-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routetypes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trad',
            new_name='RouteType',
        ),
    ]
