# Generated by Django 3.0.7 on 2020-06-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routetypes', '0002_auto_20200617_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routetype',
            old_name='gear',
            new_name='route_type',
        ),
    ]
