# Generated by Django 3.0.8 on 2020-08-01 08:04

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=django_quill.fields.QuillField(max_length=10000, verbose_name='Comment body'),
        ),
    ]
