# Generated by Django 3.0.8 on 2020-08-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200801_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='html_user',
            field=models.CharField(default='none', max_length=500, verbose_name='User name formatted in html for display'),
            preserve_default=False,
        ),
    ]
