# Generated by Django 3.0.8 on 2020-08-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_html_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='html_user',
            field=models.CharField(max_length=1000, verbose_name='User name formatted in html for display'),
        ),
    ]
