# Generated by Django 3.0.8 on 2020-10-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20200806_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_level',
            field=models.IntegerField(default=1, verbose_name='Comment nest level'),
            preserve_default=False,
        ),
    ]
