# Generated by Django 2.1.2 on 2018-10-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crags', '0002_auto_20181014_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=500, verbose_name='Route Name')),
                ('r_description', models.TextField(verbose_name='Route Description')),
                ('r_opener', models.CharField(max_length=500, verbose_name='Route Opener')),
                ('r_crag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crags.Crag', verbose_name='Crag')),
            ],
        ),
    ]
