# Generated by Django 3.0.7 on 2020-07-17 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crags', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=500, verbose_name='Route Name')),
                ('rdescription', models.TextField(verbose_name='Route Description')),
                ('ropener', models.CharField(max_length=500, verbose_name='Route Opener')),
                ('length', models.FloatField(default=0, verbose_name='Route Length')),
                ('base_unit', models.CharField(max_length=50, verbose_name='R Base_unit')),
                ('rtype', models.CharField(max_length=50, verbose_name='Type of route')),
                ('numpitch', models.CharField(max_length=500, verbose_name='Single or Multi')),
                ('avg_rating', models.FloatField(default=0, verbose_name='Average rating')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grades.Grade', verbose_name='Pitch Grade')),
                ('rcrag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crags.Crag', verbose_name='Crag')),
            ],
        ),
    ]
