# Generated by Django 3.0.8 on 2020-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20200731_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='rdescription',
            field=models.TextField(verbose_name='Route Description'),
        ),
    ]
