# Generated by Django 3.0.7 on 2020-06-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20181019_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='rlength',
            field=models.FloatField(default=0.0, verbose_name='Route Length'),
        ),
    ]
