# Generated by Django 3.0.7 on 2020-06-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_rlength'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradRoute',
            fields=[
                ('route_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routes.Route')),
            ],
            bases=('routes.route',),
        ),
    ]
