# Generated by Django 3.0.7 on 2020-06-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ascents', '0002_auto_20181021_1916'),
        ('pitches', '0005_pitch_plength'),
        ('routes', '0004_tradroute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradRoute',
        ),
    ]
