# Generated by Django 3.0.8 on 2020-07-31 18:00

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20200731_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='quilldescription',
            field=django_quill.fields.QuillField(default=''),
            preserve_default=False,
        ),
    ]
