# Generated by Django 3.0.8 on 2020-07-31 18:16

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_route_quilldescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='quilldescription',
        ),
        migrations.AlterField(
            model_name='route',
            name='rdescription',
            field=django_quill.fields.QuillField(),
        ),
    ]
