# Generated by Django 3.0.8 on 2020-08-01 08:04

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20200731_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='rdescription',
            field=django_quill.fields.QuillField(max_length=10000, verbose_name='Route description'),
        ),
    ]
