# Generated by Django 3.0.7 on 2020-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20200617_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='numpitch',
            field=models.CharField(default='Single Pitch', max_length=500, verbose_name='Single or Multi'),
        ),
    ]
