# Generated by Django 3.0.8 on 2020-08-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_grade_numgrade'),
        ('routes', '0007_auto_20200801_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.Grade', verbose_name='Pitch Grade'),
        ),
    ]
