# Generated by Django 3.0.7 on 2020-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_route_numpitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='numpitch',
            field=models.CharField(max_length=500, verbose_name='Single or Multi'),
        ),
    ]
