# Generated by Django 3.0.7 on 2020-07-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='ausgrade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='sagrade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='uiaagrade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='ukgrade',
        ),
    ]
