# Generated by Django 3.0.8 on 2020-08-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20200719_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='numgrade',
            field=models.IntegerField(default=1, verbose_name='Integer representation of grades'),
            preserve_default=False,
        ),
    ]
