# Generated by Django 3.0.8 on 2020-08-08 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('grades', '0003_grade_numgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutefinderQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(max_length=100, verbose_name='Type of route')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.City', verbose_name='Query city')),
                ('max_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Grade', verbose_name='Maximum grade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner of query')),
            ],
        ),
    ]
