# Generated by Django 3.0.8 on 2020-08-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routefinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routefinderquery',
            name='toprope',
            field=models.CharField(default='', max_length=100, verbose_name='Top rope access'),
            preserve_default=False,
        ),
    ]
