# Generated by Django 3.0.8 on 2020-08-24 11:33

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('routefinder', '0002_routefinderquery_toprope'),
    ]

    operations = [
        migrations.AddField(
            model_name='routefinderquery',
            name='location',
            field=djgeojson.fields.PointField(null=True),
        ),
    ]
