# Generated by Django 3.0.7 on 2020-07-17 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '__first__'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdescription', models.TextField(blank=True, default='', verbose_name='Pitch Description')),
                ('length', models.FloatField(default=0, verbose_name='Pitch Length')),
                ('base_unit', models.CharField(max_length=50, verbose_name='P Base_unit')),
                ('pgrade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.Grade', verbose_name='Pitch Grade')),
                ('proute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='routes.Route', verbose_name='Route')),
            ],
        ),
    ]
