# Generated by Django 3.0.7 on 2020-06-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0002_auto_20181019_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdescription', models.TextField(verbose_name='Pitch Description')),
                ('pgrade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routes.Route', verbose_name='Route')),
            ],
        ),
    ]
