# Generated by Django 3.0.7 on 2020-07-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitch',
            old_name='pgrade',
            new_name='grade',
        ),
    ]
