# Generated by Django 3.0.7 on 2020-06-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20200615_1716'),
        ('routes', '0002_auto_20181019_1622'),
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='proute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='routes.Route', verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='pgrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grades.Grade', verbose_name='Pitch Grade'),
        ),
    ]
