# Generated by Django 3.0.8 on 2020-08-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_auto_20200804_1620'),
        ('grades', '0003_grade_numgrade'),
        ('pitches', '0002_auto_20200717_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.Grade', verbose_name='Pitch Grade'),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='proute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Route', verbose_name='Route'),
        ),
    ]
