# Generated by Django 3.0.7 on 2020-06-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0004_auto_20200615_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='plength',
            field=models.FloatField(default=0.0, verbose_name='Pitch Length'),
        ),
    ]
